openapi: "3.0.2"
schemas:
  Coordinate: 
    description: The geographical coordinate information. Patterned after CLLocationCoordinate2D from iOS CoreLocation.
    type: object
    required:
      - latitude
      - longitude
    properties:
      latitude:
        description: The latitude in degrees.
        type: number
        format: double
      longitude:
        description: The longitude in degrees.
        type: number
        format: double
