openapi: 3.0.2
info:
  title: ''
  version: ''
paths: {}
components:
  schemas:
    Error:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
        details:
          type: string
      required:
        - code
        - message
      x-examples:
        Localization Error:
          code: 9999
          message: Localization Error
          details: Query image is not a valid JPEG.
