openapi: "3.0.2"
info:
  title: ''
  version: ''
paths: {}
components:
  schemas:
    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string