openapi: "3.0.2"
schemas:
  Floorplan:
    type: object
    required:
      - id
      - file
      - level
    properties:
      id:
        type: string
        format: uuid
      name:
        description: Name of the floor which will may not be a number (e.g., 'lobby', 'mezzanine', etc) or the related filename.
        type: string
      file:
        $ref: 'https://github.com/fantasmoio/api-spec/components/File.yaml'
      level:
        type: integer
        format: int32
        description: The logical floor of the building.
