openapi: "3.0.2"
schemas:
  Floorplan:
    description: A collection of references to the relationships between rooms, spaces, traffic patterns, and other physical features at one level of a structure.
    type: object
    required:
      - files
      - level
      - place
    properties:
      name:
        description: Name of the floor which will may not be a number (e.g., 'lobby', 'mezzanine', etc) or the related filename.
        type: string
      files:
        type: array
        items:
          $ref: 'https://github.com/fantasmoio/api-spec/components/file.yaml'
      level:
        type: integer
        format: int32
        description: The logical floor of the building.
      place:  
        description: ID of the place that this object represents. 
        type: string
        format: uuid