openapi: "3.0.2"
info:
  title: ""
  version: ""
paths: {}
components:
  schemas:
    Image:
      description: An image file with associated metadata.
      type: object
      required:
        - file
        - imageMetadata
      properties:
        file:
          $ref: "./File.yaml"
        imageMetadata:
          $ref: "./Image-metadata.yaml"
