openapi: "3.0.2"
info:
  title: ""
  version: ""
paths: {}
components:
  schemas:
    ImageResolution:
      description: The dimensions of the image in pixels.
      type: object
      required:
        - height
        - width
      properties:
        height:
          description: The height of the image in pixels.
          type: integer
          format: int32
        width:
          description: The width of the image in pixels.
          type: integer
          format: int32
