openapi: "3.0.2"
schemas:
  Location:
    description: Geographical information relating to a sensor measurement. 
    type: object
    required:
      - coordinate
    properties:
      coordinate:
        $ref: 'https://github.com/fantasmoio/api-spec/components/Coordinate.yaml'
      altitude:
        type: number
        format: float
        description: The altitude, measured in meters.
      floor:
        type: integer
        format: int32
        description: The logical floor of the building.
      horizontalAccuracy:
        type: number
        format: float
        description: The radius of uncertainty for the location, measured in meters.
      verticalAccuracy:
        type: number
        format: float
        description: The accuracy of the altitude value, measured in meters.
      capturedAt:
        type: number
        format: double
        description: Time in seconds since Unix Epoch that this location was captured.
