openapi: "3.0.2"
info:
  title: ""
  version: ""
paths: {}
components:
  schemas:
    Pose:
      description: The position and orientation relative to a frame of reference.
      type: object
      required:
        - position
        - quaternion
      properties:
        referenceFrame:
          description: When the reference frame is `local`, the origin of the coordinate system for this pose is relative to the device or the process that generated it. When the reference frame is `place`, the coordinate system of this pose is consistent with that of the place.
          type: string
          enum:
            - local
            - place
        position:
          $ref: "./Position.yaml"
        orientation:
          $ref: "./Orientation.yaml"
