openapi: "3.0.2"
schemas:
  Pose:
    type: object
    required:
      - position
      - quaternion
    properties:
      source:
        type: string
        enum:
        - device
        - keyframe
        - interpolated
      frame:
        type: string
        enum:
        - earth
        - local
      position:
        $ref: 'https://github.com/fantasmoio/api-spec/components/Position.yaml'
      quaternion:
        $ref: 'https://github.com/fantasmoio/api-spec/components/Quaternion.yaml'
