openapi: "3.0.2"
info:
  title: ""
  version: ""
paths: {}
components:
  schemas:
    Pose:
      description: The position and orientation relative to a frame of reference.
      type: object
      required:
        - position
        - orientation
      properties:
        referenceFrame:
          description: When the reference frame is `local`, the origin of the coordinate system for this pose is relative to the device or the process that generated it. When the reference frame is `place`, the coordinate system of this pose is consistent with that of the place.
          type: string
          enum:
            - local
            - place
        position:
          $ref: "./Position.yaml"
        orientation:
          description: If available, the orientation of the image as a unit quaternion in a local right-handed coordinate system with gravity in the positive y direction. If no gravity is provided, it is assumed that the image is perfectly gravity-aligned
          type: object
          required:
            - w
            - x
            - y
            - z
          properties:
            w:
              description: The orientation quaternion's *w* coefficient
              type: number
              format: float
            x:
              description: The orientation quaternion's *x* coefficient
              type: number
              format: float
            y:
              description: The orientation quaternion's *y* coefficient
              type: number
              format: float
            z:
              description: The orientation quaternion's *z* coefficient
              type: number
              format: float
